"""Rename category to goal

Revision ID: 23ec6ba47c52
Revises: 28e3b383de7f
Create Date: 2024-07-15 15:06:40.784706

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "23ec6ba47c52"
down_revision = "28e3b383de7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_categories")
    op.drop_table("categories")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_categories",
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name="task_categories_category_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name="task_categories_task_id_fkey"
        ),
        sa.PrimaryKeyConstraint("task_id", "category_id", name="task_categories_pkey"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("color", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="categories_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="categories_pkey"),
    )
    # ### end Alembic commands ###
